#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`;

flag=0

if [[ $USER != 'root' ]]; then
	echo "Maaf, Anda harus menjalankan ini sebagai root"
	exit
fi

MYIP=$(wget -qO- ipv4.icanhazip.com)

#vps="zvur";
vps="aneka";

if [[ $vps = "zvur" ]]; then
	source="http://scripts.gapaiasa.com"
else
	source="https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript"
fi

# go to root
cd

# check registered ip
wget -q -O IP $source/IP.txt
if ! grep -w -q $MYIP IP; then
	echo "Maaf, hanya IP yang terdaftar yang bisa menggunakan script ini!"
	if [[ $vps = "zvur" ]]; then
		echo ""
	else
		echo "Hubungi : Moch Dawn (https://web.facebook.com/profile.php?id=100013679919271)"
	fi
	rm -f /root/IP
	exit
fi

# User Status
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/user-list
mv ./user-list /usr/local/bin/user-list
chmod +x /usr/local/bin/user-list

# instal Buat Akun SSH/OpenVPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/buatakun
mv ./buatakun /usr/bin/buatakun
chmod +x /usr/bin/buatakun

# instal Generate Akun SSH/OpenVPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/generate
mv ./generate /usr/bin/generate
chmod +x /usr/bin/generate

# instal Generate Akun Trial
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/trial
mv ./trial /usr/bin/trial
chmod +x /usr/bin/trial

# instal  Ganti Password Akun SSH/VPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userpass
mv ./userpass /usr/bin/userpass
chmod +x /usr/bin/userpass

# instal Generate Akun SSH/OpenVPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userrenew
mv ./userrenew /usr/bin/userrenew
chmod +x /usr/bin/userrenew

# instal Hapus Akun SSH/OpenVPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userdelete
mv ./userdelete /usr/bin/userdelete
chmod +x /usr/bin/userdelete

# instal Cek Login Dropbear & OpenSSH
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userlogin
mv ./userlogin /usr/bin/userlogin
chmod +x /usr/bin/userlogin

# instal Auto Limit Multi Login
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/autolimit
mv ./autolimit /usr/bin/autolimit
chmod +x /usr/bin/autolimit

# instal Auto Limit Script Multi Login
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/auto-limit-script
mv ./auto-limit-script /usr/bin/auto-limit-script
chmod +x /usr/bin/auto-limit-script

# instal Melihat detail user SSH & OpenVPN 
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userdetail
mv ./userdetail /usr/bin/userdetail
chmod +x /usr/bin/userdetail

# instal Delete Akun Expire
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/deleteuserexpire
mv ./deleteuserexpire /usr/bin/deleteuserexpire
chmod +x /usr/bin/deleteuserexpire

# instal  Kill Multi Login
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/autokilluser
mv ./autokilluser /usr/bin/autokilluser
chmod +x /usr/bin/autokilluser

# instal Auto Banned Akun
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userban
mv ./userban /usr/bin/userban
chmod +x /usr/bin/userban

# instal Unbanned Akun
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userunban
mv ./userunban /usr/bin/userunban
chmod +x /usr/bin/userunban

# instal Mengunci Akun SSH & OpenVPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userlock
mv ./userlock /usr/bin/userlock
chmod +x /usr/bin/userlock

# instal Membuka user SSH & OpenVPN yang terkunci
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userunlock
mv ./userunlock /usr/bin/userunlock
chmod +x /usr/bin/userunlock

# instal Melihat daftar user yang terkick oleh perintah user-limit
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/loglimit
mv ./loglimit /usr/bin/loglimit
chmod +x /usr/bin/loglimit

# instal Melihat daftar user yang terbanned oleh perintah user-ban
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/logban
mv ./logban /usr/bin/logban
chmod +x /usr/bin/logban

# instal Buat Akun PPTP VPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/useraddpptp
mv ./useraddpptp /usr/bin/useraddpptp
chmod +x /usr/bin/useraddpptp

# instal Hapus Akun PPTP VPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userdeletepptp
mv ./userdeletepptp /usr/bin/userdeletepptp
chmod +x /usr/bin/userdeletepptp

# instal Lihat Detail Akun PPTP VPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/detailpptp
mv ./detailpptp /usr/bin/detailpptp
chmod +x /usr/bin/detailpptp

# instal Cek login PPTP VPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userloginpptp
mv ./userloginpptp /usr/bin/userloginpptp
chmod +x /usr/bin/userloginpptp

# instal Lihat Daftar User PPTP VPN
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/alluserpptp
mv ./alluserpptp /usr/bin/alluserpptp
chmod +x /usr/bin/alluserpptp

# instal Set Auto Reboot
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/autoreboot
mv ./autoreboot /usr/bin/autoreboot
chmod +x /usr/bin/autoreboot

# instal autolimitscript
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/auto-limit-script
mv ./auto-limit-script /usr/bin/auto-limit-script
chmod +x /usr/bin/auto-limit-script

# instal userdelete
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/userdelete
mv ./userdelete /usr/bin/userdelete
chmod +x /usr/bin/userdelete


# Install Menu
cd
wget https://raw.githubusercontent.com/Mochie150297/GanBatte/master/AutoScript/menu
mv ./menu /usr/local/bin/menu
chmod +x /usr/local/bin/menu
